---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: 696757124794.dkr.ecr.ap-south-1.amazonaws.com/nginx
  interval: 1m0s
