apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodapp
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: nodapp
  replicas: 3
  template:
    metadata:
      labels:
        app: nodapp
    spec:
      containers:
        - name: nodap
          image: 583413461794.dkr.ecr.ap-south-1.amazonaws.com/san:19.0.1 # {"$imagepolicy": "flux-system:node"}
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodappsvc
  namespace: default
spec:
  selector:
    app: nodapp
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
