apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nodapp
  namespace: flux-system
spec:
  image: 583413461794.dkr.ecr.ap-south-1.amazonaws.com/san
  interval: 1m0s
  secretRef:
    name: ecr-credentials-sync
